name: Workflow
on:
  push:
    branches:
      - main
      - test

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Run
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: Set up  Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r resources.txt
      - name: build pdf and html
        run: |
          mkdir out
          yaml-resume export data.yml -e html -o out/index
          # yaml-resume export data.yml -e pdf -o out/msbarbieri
      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: github-pages
          path: ./out/index.html
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
